# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!

name: codecrafters-redis
version: 0.1.0.0
license: BSD3

dependencies:
  - async
  - attoparsec
  - base >= 4.19 && < 5
  - bytestring
  - containers
  - extra
  - megaparsec
  - mtl
  - network
  - network-simple
  - parsec
  - parser-combinators
  - pipes
  - pipes-attoparsec
  - pipes-network
  - safe
  - stm
  - text-show
  - text
  - time
  - transformers

executables:
  codecrafters-redis-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
