# DON'T EDIT THIS!
#
# Codecrafters relies on this file being intact to run tests successfully. Any changes
# here will not reflect when CodeCrafters tests your code, and might even cause build
# failures.
#
# DON'T EDIT THIS!
resolver: lts-23.18

packages:
  - .

extra-deps:
  - pipes-network-0.6.5@sha256:1dd16c7dd7f70c0683052c486f4d46d89ff4ae68d0738da2efa451d452fcd657,1776
